config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'timeline#index'

  resources :users, param: :name, path: '/' do
    resources :statuses, except: :index
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_relationships_on_followed_id  (followed_id)
#  index_relationships_on_follower_id  (follower_id)
#

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User' # フォローしている人
  belongs_to :followed, class_name: 'User'  # フォローされてる人
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id            :integer          not null, primary key
#  name          :string
#  resource_type :string
#  resource_id   :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_roles_on_name                                    (name)
#  index_roles_on_name_and_resource_type_and_resource_id  (name,resource_type,resource_id)
#  index_roles_on_resource_type_and_resource_id           (resource_type,resource_id)
#

class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/status.rb
# == Schema Information
#
# Table name: statuses
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_statuses_on_user_id  (user_id)
#

class Status < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  name                   :string
#  description            :text
#  avatar                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :relationships_as_follower, class_name: 'Relationship', foreign_key: :follower_id
  has_many :relationships_as_followed, class_name: 'Relationship', foreign_key: :followed_id
  has_many :followings, through: :relationships_as_follower, source: :followed
  has_many :followers, through: :relationships_as_followed, source: :follower

  validates :name, uniqueness: true

  def to_param
    name
  end

  def timeline
    [followings, self].flatten.map(&:statuses).flatten.sort { |a, b| b.created_at <=> a.created_at }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
# frozen_string_literal: true

class StatusesController < ApplicationController
  before_action :set_user, only: :show
  before_action :set_status, only: %i[show destroy]

  def show; end

  def new
    @status = current_user.statuses.build
  end

  def create
    @status = current_user.statuses.build(status_params)
    if @status.save
      redirect_to root_url(@user), notice: 'Status was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @status.destroy
    redirect_to root_url, notice: 'Status was successfully destroyed.'
  end

  private

  def set_status
    @status = @user.statuses.find(params[:id])
  end

  def status_params
    params.fetch(:status, {}).permit(:body)
  end

  def set_user
    @user = User.find_by(name: params[:user_name])
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  before_action :check_user

  def index
    @statuses = current_user.timeline
  end

  private

  def check_user
    redirect_to new_user_session_path if current_user.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(name: params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/

    %title Witter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %y
    %nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
      .navbar-brand Witter
      %button.navbar-toggler.navbar-toggler-right{ data:{toggle: 'collapse', target:'#global-nav'}}
        %span.navbar-toggler-icon
      #global-nav.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            = link_to 'ホーム', root_path, class: 'nav-link'
          - if user_signed_in?
            %li.nav-item
              =link_to '作成', new_user_status_path(current_user), class: 'nav-link', confirm: 'Are you sure?'
            %li.nav-item
              =link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link', confirm: 'Are you sure?'
    .container
      = yield

app/views/statuses/_form.html.haml
= simple_form_for(@status, url: user_statuses_path(current_user)) do |f|
  = f.error_notification

  .form-inputs
    = f.input :body

  .form-actions
    = f.button :submit

app/views/statuses/_status.html.haml
.row.mb-3
  .col-md-12
    .card
      .card-title
        %b= link_to "@#{status.user.name}", user_path(status.user.name)
        %small.text-muted= status.created_at
      .card-text= status.body

app/views/statuses/edit.html.haml
%h1 Editing status

= render 'form'

app/views/statuses/index.html.haml
.row.pt-3
  .col-md-3
    = @user.email
  .col-md-9
    = render @statuses

app/views/statuses/new.html.haml
%h1 New status

= render 'form'

app/views/statuses/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_status_path(@status)
\|
= link_to 'Back', statuses_path

app/views/timeline/index.html.haml
= render @statuses

app/views/user/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :email
  = f.error_span :email
  = f.input :encrypted_password
  = f.error_span :encrypted_password
  = f.input :reset_password_token
  = f.error_span :reset_password_token
  = f.input :reset_password_sent_at
  = f.error_span :reset_password_sent_at
  = f.input :remember_created_at
  = f.error_span :remember_created_at
  = f.input :current_sign_in_at
  = f.error_span :current_sign_in_at
  = f.input :last_sign_in_at
  = f.error_span :last_sign_in_at
  = f.input :current_sign_in_ip
  = f.error_span :current_sign_in_ip
  = f.input :last_sign_in_ip
  = f.error_span :last_sign_in_ip
  = f.input :name
  = f.error_span :name
  = f.input :description
  = f.error_span :description
  = f.input :avatar
  = f.error_span :avatar
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/user/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/user/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:encrypted_password)
      %th= model_class.human_attribute_name(:reset_password_token)
      %th= model_class.human_attribute_name(:reset_password_sent_at)
      %th= model_class.human_attribute_name(:remember_created_at)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:avatar)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.email
        %td= user.encrypted_password
        %td= user.reset_password_token
        %td= user.reset_password_sent_at
        %td= user.remember_created_at
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td= user.name
        %td= user.description
        %td= user.avatar
        %td=l user.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/user/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/user/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @user.description
%p
  %strong= model_class.human_attribute_name(:avatar) + ':'
  %br
  = @user.avatar


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

= render @user.statuses